## name: Monochrome Muted
## author: Custom

background              #000000
foreground              #f5f5f5

selection_foreground    #000000
selection_background    #f5f5f5

cursor                  #ffffff
cursor_text_color       #000000

url_color               #cccccc

color0                  #000000
color1                  #8a5454
color2                  #58705f
color3                  #806d4b
color4                  #536f86
color5                  #705e79
color6                  #4f7473
color7                  #c6c6c6
color8                  #454545
color9                  #ad6966
color10                 #75907c
color11                 #a18757
color12                 #6d8ba3
color13                 #887294
color14                 #64908f
color15                 #f5f5f5

active_tab_foreground   #000000
active_tab_background   #f5f5f5
inactive_tab_foreground #f5f5f5
inactive_tab_background #333333
